version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    commands:
      - "apt-get update"
      - "apt-get install -y apt-transport-https ca-certificates curl software-properties-common"
      - "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -"
      - 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
      - 'apt-get update'
      - 'apt-get install -y docker-ce=17.06.0~ce-0~ubuntu'
      - 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
  pre_build:
    commands:
      - 'npm install -g yarn'
      - 'yarn install'
      - 'npm run test'
  build:
    commands:
      - 'yarn run build'
  post_build:
    commands:
      - 'docker build -t exchange321/accese-web-client:latest -f .docker/Dockerfile .'
      - 'docker push exchange321/accese-web-client:latest'
