version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    commands:
      - 'sudo apt-get update'
      - 'curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -'
      - 'sudo apt-get install -y nodejs'
      - 'sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
  pre_build:
    commands:
      - 'sudo npm install'
      - 'sudo npm run test'
  build:
    commands:
      - 'sudo npm run build'
  post_build:
    commands:
      - 'sudo docker build -t exchange321/accese-web-client:latest -f .docker/Dockerfile .'
      - 'sudo docker push exchange321/accese-web-client:latest'
artifacts:
  files:
    - 'appspec.yml'
