version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    commands:
      - 'apt-get update'
      - 'curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -'
      - 'apt-get install -y nodejs'
      - 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
  pre_build:
    commands:
      - 'npm install'
      - 'npm run test'
  build:
    commands:
      - 'yarn run build'
  post_build:
    commands:
      - 'docker build -t exchange321/accese-web-client:latest -f .docker/Dockerfile .'
      - 'docker push exchange321/accese-web-client:latest'
