export const APP_ACTIONS = {
  HANDLE_QUERY_CHANGE: 'HANDLE_APP_PAGE_SEARCH_QUERY_CHANGE',
  TRIGGER_SEARCH_STATE: 'TRIGGER_APP_PAGE_SEARCH_STATE',
  UPDATE_SEARCH_SUGGESTIONS: 'UPDATE_APP_PAGE_SEARCH_SUGGESTIONS',
};

export default {};
