export const APP_ACTIONS = {
  HANDLE_QUERY_CHANGE: 'HANDLE_APP_PAGE_SEARCH_QUERY_CHANGE',
  TRIGGER_SEARCH_STATE: 'TRIGGER_APP_PAGE_SEARCH_STATE',
  UPDATE_SEARCH_SUGGESTIONS: 'UPDATE_APP_PAGE_SEARCH_SUGGESTIONS',
  UPDATE_SEARCH_RESULTS: 'UPDATE_APP_PAGE_SEARCH_RESULTS',
  ENABLE_SERVICE_WORKER: 'ENABLE_APP_SERVICE_WORKER_SUPPORT',
  DISABLE_SERVICE_WORKER: 'DISABLE_APP_SERVICE_WORKER_SUPPORT',
};

export default {};
